name: Build And Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version to build'
        required: true
        default: 'v'
        type: string
      build-shared-libs:
        description: 'Build shared libraries'
        required: false
        default: true
        type: boolean
      build-static-libs:
        description: 'Build static libraries'
        required: false
        default: false
        type: boolean
      build-wheels:
        description: 'Build wheels'
        required: false
        default: false
        type: boolean
      linux-build:
        description: 'Build for Linux'
        required: false
        default: true
        type: boolean
      linux-arm64-build:
        description: 'Build for Linux ARM64'
        required: false
        default: false
        type: boolean
      macos-build:
        description: 'Build for macOS'
        required: false
        default: false
        type: boolean
      windows-build:
        description: 'Build for Windows'
        required: false
        default: false
        type: boolean
      android-build:
        description: 'Build for Android'
        required: false
        default: false
        type: boolean
      publish:
        description: 'Publish the library'
        required: false
        default: true
        type: boolean
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix
        id: set-matrix
        run: |
          build_list=""
          if [[ "${{ github.event.inputs.linux-build }}" == "true" ]]; then
            build_list+=",{\"os\":\"ubuntu-latest\",\"shared_name\":\"linux-x86_64\"}"
          fi
          if [[ "${{ github.event.inputs.linux-arm64-build }}" == "true" ]]; then
            build_list+=",{\"os\":\"arm64-server\",\"shared_name\":\"linux-arm64\"}"
          fi
          if [[ "${{ github.event.inputs.macos-build }}" == "true" ]]; then
            build_list+=",{\"os\":\"macos-15\",\"shared_name\":\"macos-arm64\"}"
          fi
          if [[ "${{ github.event.inputs.windows-build }}" == "true" ]]; then
            build_list+=",{\"os\":\"windows-2022\",\"shared_name\":\"windows-x86_64\"}"
          fi
          if [[ -n "$build_list" ]]; then
            build_list="${build_list:1}"
          fi
          matrix=$(echo "{\"include\":[$build_list]}")
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build:
    if: github.event.inputs.build-wheels == 'true' || github.event.inputs.build-shared-libs == 'true' || github.event.inputs.build-static-libs == 'true'
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: '8.3'

      - name: Set up environment
        run: |
          echo "Running on ${{ matrix.os }} with shared target name: ${{ matrix.shared_name }}"

      - name: Build shared libraries
        if: ${{ github.event.inputs.build-shared-libs == 'true' }}
        run: |
          echo "Building shared libraries for ${{ matrix.shared_name }}..."
          chmod +x ./scripts/build-shared.sh
          ./scripts/build-shared.sh
      
      - name: Build static libraries
        if: ${{ github.event.inputs.build-static-libs == 'true' }}
        run: |
          echo "Building static libraries for ${{ matrix.shared_name }}..."
          chmod +x ./scripts/build-static.sh
          ./scripts/build-static.sh "${{ matrix.shared_name }}"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.shared_name }}
          path: build/output/

  publish:
    if: github.event.inputs.publish == 'true'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: build_artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: build_artifacts/**/*

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
