name: Build and Release Swoole Shared Library

on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with "v"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build environment
        run: |
          echo "Starting build on ${{ matrix.os }}..."
          # You can install dependencies here if needed

      - name: Build Swoole shared library
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            echo "Building for Linux..."
            chmod +x ./build-linux.sh
            ./build-linux.sh
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            echo "Building for macOS..."
            chmod +x ./build-macos.sh
            ./build-macos.sh
          else
            echo "Building for Windows..."
            powershell.exe -File build-windows.ps1
          fi

      - name: Verify Swoole Installation (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: docker run --rm phpswoole/swoole "php --ri swoole"

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: swoole-${{ matrix.os }}
          path: build/output/

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          path: build_artifacts

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: Automated release of Swoole shared library version ${{ github.ref }}.

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: build_artifacts/**/*
